---
- name: Install Arch Linux from an Arch ISO
  hosts: localhost
  tasks:
    - name: Check internet connectivity
      wait_for:
        host: archlinux.org
        port: 80

    - name: Enable ntp
      command: /usr/bin/timedatectl set-ntp true

    - name: Enable ntp
      command: /usr/bin/timedatectl status
      register: ntp
    - debug: msg="{{ ntp.stdout }}"
    - debug: msg="{{ ntp.stderr }}"
